/* CURRICULUM — single source of truth for academic tracking (generated 2026-07-17
   from lessons-data.js + content/lesson-NN.js; regenerate with the gen-curriculum
   script if steps are added/removed). id = stable internal lesson number (file/
   LESSON_CONTENT key); label = visible Unit.Lesson number. Learn-by-Doing IDs are
   'sN' = index of the step carrying a try-activity. Games/practice/vocab/hook are
   NOT listed and never count toward academic progress. */
const CURRICULUM={
 courseId:"practical-music-theory",
 courseTitle:"Practical Music Theory",
 version:1,
 units:[
  {unit:1, title:"Basic Concepts"},
  {unit:2, title:"Rhythm I"},
  {unit:3, title:"Expression Marks"},
  {unit:4, title:"Major Scales and Key Signatures"},
  {unit:5, title:"Intervals"},
  {unit:6, title:"Rhythm II"},
  {unit:7, title:"Triads"},
  {unit:8, title:"Minor Scales and Modes"},
  {unit:9, title:"Roman Numerals and Cadences"},
  {unit:10, title:"Seventh Chords"},
  {unit:11, title:"Harmony Foundations"},
  {unit:12, title:"Nonchord Tones and Ornaments"},
  {unit:13, title:"Tonicization and Modulation"},
  {unit:14, title:"Form and Texture"},
  {unit:15, title:"Chromatic and Contemporary Harmony"}
 ],
 pages:[
  {id:1, label:"1.1", unit:1, title:"The Staff, Notes and Pitches", route:"lessons/lesson-01.html", lbdIds:["s0","s1","s2","s3","s4"], hasQuiz:true, status:"active", version:1},
  {id:2, label:"1.2", unit:1, title:"Treble Clef and Staff", route:"lessons/lesson-02.html", lbdIds:["s0","s1","s2","s3","s4","s5"], hasQuiz:true, status:"active", version:1},
  {id:3, label:"1.3", unit:1, title:"Bass Clef and Staff", route:"lessons/lesson-03.html", lbdIds:["s0","s1","s2","s3","s4","s5"], hasQuiz:true, status:"active", version:1},
  {id:4, label:"1.4", unit:1, title:"The Grand Staff and Ledger Lines (the middle notes)", route:"lessons/lesson-04.html", lbdIds:["s0","s1","s2","s3","s4","s5"], hasQuiz:true, status:"active", version:1},
  {id:5, label:"1.5", unit:1, title:"Ledger Lines (low and high notes)", route:"lessons/lesson-05.html", lbdIds:["s0","s1","s2","s3","s4","s5"], hasQuiz:true, status:"active", version:1},
  {id:6, label:"1.6", unit:1, title:"Flats", route:"lessons/lesson-06.html", lbdIds:["s0","s1","s2","s3","s4"], hasQuiz:true, status:"active", version:1},
  {id:7, label:"1.7", unit:1, title:"Sharps", route:"lessons/lesson-07.html", lbdIds:["s0","s1","s2","s3","s4"], hasQuiz:true, status:"active", version:1},
  {id:8, label:"1.8", unit:1, title:"Naturals", route:"lessons/lesson-08.html", lbdIds:["s0","s1","s2","s3","s4"], hasQuiz:true, status:"active", version:1},
  {id:9, label:"1.9", unit:1, title:"Whole Steps, Half Steps and Enharmonic Notes", route:"lessons/lesson-09.html", lbdIds:["s0","s1","s2","s3","s4"], hasQuiz:true, status:"active", version:1},
  {id:10, label:"2.1", unit:2, title:"Note Values", route:"lessons/lesson-10.html", lbdIds:["s0","s1","s2","s3","s4"], hasQuiz:true, status:"active", version:1},
  {id:11, label:"2.2", unit:2, title:"Measure, Bar Line and Double Bar", route:"lessons/lesson-11.html", lbdIds:["s0","s1","s2","s4"], hasQuiz:true, status:"active", version:1},
  {id:12, label:"2.3", unit:2, title:"4/4 Time Signature and Note Values", route:"lessons/lesson-12.html", lbdIds:["s0","s1","s2","s3","s4","s5"], hasQuiz:true, status:"active", version:1},
  {id:13, label:"2.4", unit:2, title:"Whole, Half and Quarter Rests", route:"lessons/lesson-13.html", lbdIds:["s0","s1","s2","s3","s4"], hasQuiz:true, status:"active", version:1},
  {id:14, label:"2.5", unit:2, title:"2/4 Time Signature", route:"lessons/lesson-14.html", lbdIds:["s0","s1","s2","s3","s4","s5"], hasQuiz:true, status:"active", version:1},
  {id:15, label:"2.6", unit:2, title:"3/4 Time Signature", route:"lessons/lesson-15.html", lbdIds:["s0","s1","s2","s3","s4"], hasQuiz:true, status:"active", version:1},
  {id:16, label:"2.7", unit:2, title:"Dotted Half Note", route:"lessons/lesson-16.html", lbdIds:["s0","s1","s2","s3","s4","s5"], hasQuiz:true, status:"active", version:1},
  {id:17, label:"2.8", unit:2, title:"Ties and Slurs", route:"lessons/lesson-17.html", lbdIds:["s0","s1","s2","s3","s4"], hasQuiz:true, status:"active", version:1},
  {id:18, label:"2.9", unit:2, title:"Eighth Notes", route:"lessons/lesson-18.html", lbdIds:["s0","s1","s2","s3","s4","s5"], hasQuiz:true, status:"active", version:1},
  {id:19, label:"2.10", unit:2, title:"Eighth Rests", route:"lessons/lesson-19.html", lbdIds:["s0","s1","s2","s3","s4"], hasQuiz:true, status:"active", version:1},
  {id:20, label:"2.11", unit:2, title:"Dotted Quarter Note", route:"lessons/lesson-20.html", lbdIds:["s0","s1","s2","s3","s4","s5"], hasQuiz:true, status:"active", version:1},
  {id:21, label:"3.1", unit:3, title:"Dynamic Signs", route:"lessons/lesson-21.html", lbdIds:["s0","s1","s2","s3","s4"], hasQuiz:true, status:"active", version:1},
  {id:22, label:"3.2", unit:3, title:"Tempo Marks", route:"lessons/lesson-22.html", lbdIds:["s0","s1","s2","s3","s4"], hasQuiz:true, status:"active", version:1},
  {id:23, label:"3.3", unit:3, title:"Articulation", route:"lessons/lesson-23.html", lbdIds:["s0","s1","s2","s3","s4"], hasQuiz:true, status:"active", version:1},
  {id:24, label:"3.4", unit:3, title:"Repeat Sign, 1st and 2nd Endings", route:"lessons/lesson-24.html", lbdIds:["s0","s1","s2","s3","s4"], hasQuiz:true, status:"active", version:1},
  {id:25, label:"3.5", unit:3, title:"D.C., D.S., Coda and Fine", route:"lessons/lesson-25.html", lbdIds:["s0","s1","s2","s3","s4","s5"], hasQuiz:true, status:"active", version:1},
  {id:26, label:"4.1", unit:4, title:"Tetrachords and Major Scales", route:"lessons/lesson-26.html", lbdIds:["s0","s1","s2","s3","s4","s5"], hasQuiz:true, status:"active", version:1},
  {id:27, label:"4.2", unit:4, title:"The Sharp Scales — G and D Major", route:"lessons/lesson-27.html", lbdIds:["s0","s1","s2","s3","s4","s5"], hasQuiz:true, status:"active", version:1},
  {id:28, label:"4.3", unit:4, title:"The Flat Scales — F and B♭ Major", route:"lessons/lesson-28.html", lbdIds:["s0","s1","s2","s3","s4","s5"], hasQuiz:true, status:"active", version:1},
  {id:29, label:"4.4", unit:4, title:"Key Signatures — The Sharp Keys", route:"lessons/lesson-29.html", lbdIds:["s0","s1","s2","s3","s4","s5"], hasQuiz:true, status:"active", version:1},
  {id:30, label:"4.5", unit:4, title:"Key Signatures — The Flat Keys", route:"lessons/lesson-30.html", lbdIds:["s0","s1","s2","s3","s4","s5"], hasQuiz:true, status:"active", version:1},
  {id:31, label:"4.6", unit:4, title:"Circle of Fifths and Enharmonic Keys", route:"lessons/lesson-31.html", lbdIds:["s0","s1","s2","s3","s4","s5","s6","s7"], hasQuiz:true, status:"active", version:1},
  {id:32, label:"4.7", unit:4, title:"Solfège and Transposition", route:"lessons/lesson-32.html", lbdIds:["s0","s1","s2","s3","s4","s5","s6","s7"], hasQuiz:true, status:"active", version:1},
  {id:33, label:"5.1", unit:5, title:"Intervals", route:"lessons/lesson-33.html", lbdIds:["s0","s1","s2","s3","s4"], hasQuiz:true, status:"active", version:1},
  {id:34, label:"5.2", unit:5, title:"Perfect and Major Intervals", route:"lessons/lesson-34.html", lbdIds:["s0","s1","s2","s3","s4","s5","s6","s7"], hasQuiz:true, status:"active", version:1},
  {id:35, label:"5.3", unit:5, title:"Minor Intervals", route:"lessons/lesson-35.html", lbdIds:["s0","s1","s2","s3","s4","s5","s6","s7"], hasQuiz:true, status:"active", version:1},
  {id:36, label:"5.4", unit:5, title:"Augmented and Diminished Intervals", route:"lessons/lesson-36.html", lbdIds:["s0","s1","s2","s3","s4","s5","s6","s7"], hasQuiz:true, status:"active", version:1},
  {id:37, label:"5.5", unit:5, title:"Interval Inversions and Compound Intervals", route:"lessons/lesson-37.html", lbdIds:["s0","s1","s2","s3","s4","s5","s6"], hasQuiz:true, status:"active", version:1},
  {id:38, label:"6.1", unit:6, title:"Sixteenth Notes", route:"lessons/lesson-38.html", lbdIds:["s0","s1","s2","s3","s4","s5"], hasQuiz:true, status:"active", version:1},
  {id:39, label:"6.2", unit:6, title:"Sixteenth Rests", route:"lessons/lesson-39.html", lbdIds:["s0","s1","s2","s3","s4","s5"], hasQuiz:true, status:"active", version:1},
  {id:40, label:"6.3", unit:6, title:"Dotted Eighth Notes", route:"lessons/lesson-40.html", lbdIds:["s0","s1","s2","s3","s4","s5","s6"], hasQuiz:true, status:"active", version:1},
  {id:41, label:"6.4", unit:6, title:"Common Time and Cut Time (Alla Breve)", route:"lessons/lesson-41.html", lbdIds:["s0","s1","s2","s3","s4","s5"], hasQuiz:true, status:"active", version:1},
  {id:42, label:"6.5", unit:6, title:"3/8 and 6/8 Time Signatures", route:"lessons/lesson-42.html", lbdIds:["s0","s1","s2","s3","s4","s5"], hasQuiz:true, status:"active", version:1},
  {id:43, label:"6.6", unit:6, title:"Compound Meter Expanded", route:"lessons/lesson-43.html", lbdIds:["s0","s1","s2","s3","s4","s5","s6","s7","s8","s9","s10"], hasQuiz:true, status:"active", version:1},
  {id:44, label:"6.7", unit:6, title:"Eighth Note Triplets", route:"lessons/lesson-44.html", lbdIds:["s0","s1","s2","s3","s4","s5"], hasQuiz:true, status:"active", version:1},
  {id:45, label:"6.8", unit:6, title:"Tuplets: Triplets and Duplets", route:"lessons/lesson-45.html", lbdIds:["s0","s1","s2","s3","s4","s5","s6"], hasQuiz:true, status:"active", version:1},
  {id:46, label:"6.9", unit:6, title:"Incomplete Measures (Pick-up Notes) and Syncopation", route:"lessons/lesson-46.html", lbdIds:["s0","s1","s2","s3","s4","s5"], hasQuiz:true, status:"active", version:1},
  {id:47, label:"6.10", unit:6, title:"Syncopation", route:"lessons/lesson-47.html", lbdIds:["s0","s1","s2","s3","s4","s5","s6"], hasQuiz:true, status:"active", version:1},
  {id:48, label:"6.11", unit:6, title:"Asymmetrical and Changing Meter", route:"lessons/lesson-48.html", lbdIds:["s0","s1","s2","s3","s4","s5","s6"], hasQuiz:true, status:"active", version:1},
  {id:49, label:"7.1", unit:7, title:"Triads", route:"lessons/lesson-49.html", lbdIds:["s0","s1","s2","s3","s4","s5"], hasQuiz:true, status:"active", version:1},
  {id:50, label:"7.2", unit:7, title:"Scale Degree Names", route:"lessons/lesson-50.html", lbdIds:["s0","s1","s2","s3","s4","s5"], hasQuiz:true, status:"active", version:1},
  {id:51, label:"7.3", unit:7, title:"Primary and Major Triads", route:"lessons/lesson-51.html", lbdIds:["s0","s1","s2","s3","s4","s5"], hasQuiz:true, status:"active", version:1},
  {id:52, label:"7.4", unit:7, title:"Diatonic Triads", route:"lessons/lesson-52.html", lbdIds:["s0","s1","s2","s3","s4","s5","s6"], hasQuiz:true, status:"active", version:1},
  {id:53, label:"7.5", unit:7, title:"Minor Triads", route:"lessons/lesson-53.html", lbdIds:["s0","s1","s2","s3","s4","s5","s6"], hasQuiz:true, status:"active", version:1},
  {id:54, label:"7.6", unit:7, title:"Augmented and Diminished Triads", route:"lessons/lesson-54.html", lbdIds:["s0","s1","s2","s3","s4","s5","s6"], hasQuiz:true, status:"active", version:1},
  {id:55, label:"7.7", unit:7, title:"Triads — 1st Inversion", route:"lessons/lesson-55.html", lbdIds:["s0","s1","s2","s3","s4","s5","s6","s7"], hasQuiz:true, status:"active", version:1},
  {id:56, label:"7.8", unit:7, title:"Triads — 2nd Inversion", route:"lessons/lesson-56.html", lbdIds:["s0","s1","s2","s3","s4","s5","s6","s7"], hasQuiz:true, status:"active", version:1},
  {id:57, label:"7.9", unit:7, title:"Figured Bass", route:"lessons/lesson-57.html", lbdIds:["s0","s1","s2","s3","s4","s5","s6","s7"], hasQuiz:true, status:"active", version:1},
  {id:58, label:"8.1", unit:8, title:"Minor Scales", route:"lessons/lesson-58.html", lbdIds:["s0","s1","s2","s3","s4","s5"], hasQuiz:true, status:"active", version:1},
  {id:59, label:"8.2", unit:8, title:"Natural, Harmonic and Melodic Minor Scales", route:"lessons/lesson-59.html", lbdIds:["s0","s1","s2","s3","s4","s5","s6","s7"], hasQuiz:true, status:"active", version:1},
  {id:60, label:"8.3", unit:8, title:"The Primary Triads in Minor Keys", route:"lessons/lesson-60.html", lbdIds:["s0","s1","s2","s3","s4","s5","s6"], hasQuiz:true, status:"active", version:1},
  {id:61, label:"8.4", unit:8, title:"Modes Related to the Major Scale: Ionian, Mixolydian and Lydian", route:"lessons/lesson-61.html", lbdIds:["s0","s1","s2","s3","s4","s5","s6"], hasQuiz:true, status:"active", version:1},
  {id:62, label:"8.5", unit:8, title:"Modes Related to the Minor Scale: Aeolian, Dorian, Phrygian, Locrian", route:"lessons/lesson-62.html", lbdIds:["s0","s1","s2","s3","s4","s5","s6"], hasQuiz:true, status:"active", version:1},
  {id:63, label:"8.6", unit:8, title:"Modes in Practice", route:"lessons/lesson-63.html", lbdIds:["s0","s1","s2","s3","s4","s5","s6"], hasQuiz:true, status:"active", version:1},
  {id:64, label:"8.7", unit:8, title:"Pentatonic Scales", route:"lessons/lesson-64.html", lbdIds:["s0","s1","s2","s3","s4","s5","s6"], hasQuiz:true, status:"active", version:1},
  {id:65, label:"8.8", unit:8, title:"Chromatic Scale", route:"lessons/lesson-65.html", lbdIds:["s0","s1","s2","s3"], hasQuiz:true, status:"active", version:1},
  {id:66, label:"8.9", unit:8, title:"Whole-Tone and Chromatic Scales", route:"lessons/lesson-66.html", lbdIds:["s0","s1","s2","s3","s4","s5","s6"], hasQuiz:true, status:"active", version:1},
  {id:67, label:"9.1", unit:9, title:"Roman Numeral Analysis", route:"lessons/lesson-67.html", lbdIds:["s0","s1","s2","s3","s4","s5","s6","s7"], hasQuiz:true, status:"active", version:1},
  {id:68, label:"9.2", unit:9, title:"Cadences", route:"lessons/lesson-68.html", lbdIds:["s0","s1","s2","s3","s4","s5","s6","s7"], hasQuiz:true, status:"active", version:1},
  {id:69, label:"9.3", unit:9, title:"Major Chord Progressions", route:"lessons/lesson-69.html", lbdIds:["s0","s1","s2","s3","s4","s5","s6"], hasQuiz:true, status:"active", version:1},
  {id:70, label:"9.4", unit:9, title:"Minor Chord Progressions", route:"lessons/lesson-70.html", lbdIds:["s0","s1","s2","s3","s4","s5","s6"], hasQuiz:true, status:"active", version:1},
  {id:71, label:"10.1", unit:10, title:"The V7 (Dominant 7th) Chord", route:"lessons/lesson-71.html", lbdIds:["s0","s1","s2","s3","s4","s5"], hasQuiz:true, status:"active", version:1},
  {id:72, label:"10.2", unit:10, title:"V7 Chord — 1st, 2nd and 3rd Inversions", route:"lessons/lesson-72.html", lbdIds:["s0","s1","s2","s3","s4","s5","s6"], hasQuiz:true, status:"active", version:1},
  {id:73, label:"10.3", unit:10, title:"Five Common Seventh-Chord Types", route:"lessons/lesson-73.html", lbdIds:["s0","s1","s2","s3","s4","s5","s6"], hasQuiz:true, status:"active", version:1},
  {id:74, label:"10.4", unit:10, title:"Seventh-Chord Inversions", route:"lessons/lesson-74.html", lbdIds:["s0","s1","s2","s3","s4","s5","s6","s7"], hasQuiz:true, status:"active", version:1},
  {id:75, label:"10.5", unit:10, title:"Lead Sheet Reading (Chord Symbols)", route:"lessons/lesson-75.html", lbdIds:["s0","s1","s2","s3","s4","s5","s6"], hasQuiz:true, status:"active", version:1},
  {id:76, label:"11.1", unit:11, title:"Common Chord Progressions", route:"lessons/lesson-76.html", lbdIds:["s0","s1","s2","s3","s4","s5","s6"], hasQuiz:true, status:"active", version:1},
  {id:77, label:"11.2", unit:11, title:"Voice-Leading Basics", route:"lessons/lesson-77.html", lbdIds:["s0","s1","s2","s3","s4","s5","s6","s7"], hasQuiz:true, status:"active", version:1},
  {id:78, label:"11.3", unit:11, title:"Harmonizing a Melody in a Major Key", route:"lessons/lesson-78.html", lbdIds:["s0","s1","s2","s3","s4","s5","s6"], hasQuiz:true, status:"active", version:1},
  {id:79, label:"11.4", unit:11, title:"Harmonizing a Melody in a Minor Key", route:"lessons/lesson-79.html", lbdIds:["s0","s1","s2","s3","s4","s5","s6"], hasQuiz:true, status:"active", version:1},
  {id:80, label:"11.5", unit:11, title:"Broken Chords and Arpeggiated Accompaniments", route:"lessons/lesson-80.html", lbdIds:["s0","s1","s2","s3","s4","s5","s6"], hasQuiz:true, status:"active", version:1},
  {id:81, label:"11.6", unit:11, title:"Composing a Melody in a Major Key", route:"lessons/lesson-81.html", lbdIds:["s0","s1","s2","s3","s4","s5","s6"], hasQuiz:true, status:"active", version:1},
  {id:82, label:"11.7", unit:11, title:"Composing a Melody in a Minor Key", route:"lessons/lesson-82.html", lbdIds:["s0","s1","s2","s3","s4","s5","s6"], hasQuiz:true, status:"active", version:1},
  {id:83, label:"11.8", unit:11, title:"12-Bar Blues Chord Progression", route:"lessons/lesson-83.html", lbdIds:["s0","s1","s2","s3","s4","s5","s6"], hasQuiz:true, status:"active", version:1},
  {id:84, label:"11.9", unit:11, title:"The Blues Scale", route:"lessons/lesson-84.html", lbdIds:["s0","s1","s2","s3","s4","s5","s6"], hasQuiz:true, status:"active", version:1},
  {id:85, label:"12.1", unit:12, title:"Passing and Neighboring Tones", route:"lessons/lesson-85.html", lbdIds:["s0","s1","s2","s3","s4","s5","s6"], hasQuiz:true, status:"active", version:1},
  {id:86, label:"12.2", unit:12, title:"Nonchord Tones Expanded", route:"lessons/lesson-86.html", lbdIds:["s0","s1","s2","s3","s4","s5","s6"], hasQuiz:true, status:"active", version:1},
  {id:87, label:"12.3", unit:12, title:"Ornaments", route:"lessons/lesson-87.html", lbdIds:["s0","s1","s2","s3","s4","s5","s6"], hasQuiz:true, status:"active", version:1},
  {id:88, label:"13.1", unit:13, title:"Secondary Dominants", route:"lessons/lesson-88.html", lbdIds:["s0","s1","s2","s3","s4","s5","s6"], hasQuiz:true, status:"active", version:1},
  {id:89, label:"13.2", unit:13, title:"Modulation", route:"lessons/lesson-89.html", lbdIds:["s0","s1","s2","s3","s4","s5","s6"], hasQuiz:true, status:"active", version:1},
  {id:90, label:"14.1", unit:14, title:"Basic Forms of Music — Motive and Phrase", route:"lessons/lesson-90.html", lbdIds:["s0","s1","s2","s3","s4","s5","s6"], hasQuiz:true, status:"active", version:1},
  {id:91, label:"14.2", unit:14, title:"Phrases and Periods", route:"lessons/lesson-91.html", lbdIds:["s0","s1","s2","s3","s4","s5","s6"], hasQuiz:true, status:"active", version:1},
  {id:92, label:"14.3", unit:14, title:"Melodic Sequence", route:"lessons/lesson-92.html", lbdIds:["s0","s1","s2","s3","s4","s5","s6"], hasQuiz:true, status:"active", version:1},
  {id:93, label:"14.4", unit:14, title:"Texture", route:"lessons/lesson-93.html", lbdIds:["s0","s1","s2","s3","s4","s5","s6"], hasQuiz:true, status:"active", version:1},
  {id:94, label:"14.5", unit:14, title:"Binary Form", route:"lessons/lesson-94.html", lbdIds:["s0","s1","s2","s3","s4","s5","s6","s7","s8","s9"], hasQuiz:true, status:"active", version:1},
  {id:95, label:"14.6", unit:14, title:"ABA (Ternary) Form", route:"lessons/lesson-95.html", lbdIds:["s0","s1","s2","s3","s4","s5","s6","s7"], hasQuiz:true, status:"active", version:1},
  {id:96, label:"14.7", unit:14, title:"Rondo Form", route:"lessons/lesson-96.html", lbdIds:["s0","s1","s2","s3","s4","s5","s6","s7"], hasQuiz:true, status:"active", version:1},
  {id:97, label:"14.8", unit:14, title:"Common Song Forms", route:"lessons/lesson-97.html", lbdIds:["s0","s1","s2","s3","s4","s5","s6"], hasQuiz:true, status:"active", version:1},
  {id:98, label:"14.9", unit:14, title:"Theme and Variations", route:"lessons/lesson-98.html", lbdIds:["s0","s1","s2","s3","s4","s5","s6"], hasQuiz:true, status:"active", version:1},
  {id:99, label:"14.10", unit:14, title:"Sonata Form", route:"lessons/lesson-99.html", lbdIds:["s0","s1","s2","s3","s4","s5","s6"], hasQuiz:true, status:"active", version:1},
  {id:100, label:"14.11", unit:14, title:"Instrumental Forms and Multi-Movement Genres", route:"lessons/lesson-100.html", lbdIds:["s0","s1","s2","s3","s4","s5","s6"], hasQuiz:true, status:"active", version:1},
  {id:101, label:"15.1", unit:15, title:"Leading-Tone Chords", route:"lessons/lesson-101.html", lbdIds:["s0","s1","s2","s3","s4","s5"], hasQuiz:true, status:"active", version:1},
  {id:102, label:"15.2", unit:15, title:"The Neapolitan Chord", route:"lessons/lesson-102.html", lbdIds:["s0","s1","s2","s3","s4","s5"], hasQuiz:true, status:"active", version:1},
  {id:103, label:"15.3", unit:15, title:"Augmented-Sixth Chords", route:"lessons/lesson-103.html", lbdIds:["s0","s1","s2","s3","s4","s5","s6","s7","s8","s9"], hasQuiz:true, status:"active", version:1},
  {id:104, label:"15.4", unit:15, title:"Borrowed Chords and Modal Mixture", route:"lessons/lesson-104.html", lbdIds:["s0","s1","s2","s3","s4","s5","s6","s7","s8","s9"], hasQuiz:true, status:"active", version:1},
  {id:105, label:"15.5", unit:15, title:"Extended Chords", route:"lessons/lesson-105.html", lbdIds:["s0","s1","s2","s3","s4","s5","s6","s7","s8","s9","s10","s11","s12"], hasQuiz:true, status:"active", version:1},
  {id:106, label:"15.6", unit:15, title:"Modern Color Chords: Sus, Add, and Sixth Chords", route:"lessons/lesson-106.html", lbdIds:["s0","s1","s2","s3","s4","s5","s6","s7","s8","s9","s10","s11","s12","s13","s14"], hasQuiz:true, status:"active", version:1},
  {id:107, label:"15.7", unit:15, title:"Introduction to Reharmonization: Substitution and Chromatic Color", route:"lessons/lesson-107.html", lbdIds:["s0","s1","s2","s3","s4","s5","s6","s7","s8","s9","s10","s11"], hasQuiz:true, status:"active", version:1}
 ]
};
if(typeof module!=="undefined") module.exports=CURRICULUM;
