/* Music Fundamentals v2 — master lesson list (15-unit reorg, 2026-07-17)
   Drives ALL navigation. n = internal sequential number (files/content keys);
   label = Unit.Lesson display number; book = source AEMT book (provenance). */
const LESSONS=[
 {n:1, label:"1.1", title:"The Staff, Notes and Pitches", unit:1, book:1, time:15, kw:["staff","note","pitch","lines","spaces"]},
 {n:2, label:"1.2", title:"Treble Clef and Staff", unit:1, book:1, time:15, kw:["treble","clef","G clef","EGBDF","FACE"]},
 {n:3, label:"1.3", title:"Bass Clef and Staff", unit:1, book:1, time:15, kw:["bass","clef","F clef","GBDFA","ACEG"]},
 {n:4, label:"1.4", title:"The Grand Staff and Ledger Lines (the middle notes)", unit:1, book:1, time:15, kw:["grand staff","ledger","middle C","brace"]},
 {n:5, label:"1.5", title:"Ledger Lines (low and high notes)", unit:1, book:1, time:15, kw:["ledger","lines","high","low"]},
 {n:6, label:"1.6", title:"Flats", unit:1, book:1, time:15, kw:["flat","accidental"]},
 {n:7, label:"1.7", title:"Sharps", unit:1, book:1, time:15, kw:["sharp","accidental"]},
 {n:8, label:"1.8", title:"Naturals", unit:1, book:1, time:15, kw:["natural","accidental"]},
 {n:9, label:"1.9", title:"Whole Steps, Half Steps and Enharmonic Notes", unit:1, book:1, time:15, kw:["whole step","half step","enharmonic"]},
 {n:10, label:"2.1", title:"Note Values", unit:2, book:1, time:15, kw:["whole","half","quarter","note values","rhythm"]},
 {n:11, label:"2.2", title:"Measure, Bar Line and Double Bar", unit:2, book:1, time:15, kw:["measure","bar line","double bar"]},
 {n:12, label:"2.3", title:"4/4 Time Signature and Note Values", unit:2, book:1, time:15, kw:["time signature","4/4","meter"]},
 {n:13, label:"2.4", title:"Whole, Half and Quarter Rests", unit:2, book:1, time:15, kw:["rest","silence"]},
 {n:14, label:"2.5", title:"2/4 Time Signature", unit:2, book:1, time:15, kw:["2/4","time signature"]},
 {n:15, label:"2.6", title:"3/4 Time Signature", unit:2, book:1, time:15, kw:["3/4","waltz","time signature"]},
 {n:16, label:"2.7", title:"Dotted Half Note", unit:2, book:1, time:15, kw:["dotted","half note","dot"]},
 {n:17, label:"2.8", title:"Ties and Slurs", unit:2, book:1, time:15, kw:["tie","slur","legato"]},
 {n:18, label:"2.9", title:"Eighth Notes", unit:2, book:1, time:15, kw:["eighth","beam","flag"]},
 {n:19, label:"2.10", title:"Eighth Rests", unit:2, book:1, time:15, kw:["eighth rest"]},
 {n:20, label:"2.11", title:"Dotted Quarter Note", unit:2, book:1, time:15, kw:["dotted quarter"]},
 {n:21, label:"3.1", title:"Dynamic Signs", unit:3, book:1, time:15, kw:["dynamics","forte","piano","crescendo"]},
 {n:22, label:"3.2", title:"Tempo Marks", unit:3, book:1, time:15, kw:["tempo","allegro","andante","adagio"]},
 {n:23, label:"3.3", title:"Articulation", unit:3, book:1, time:15, kw:["staccato","accent","legato","fermata"]},
 {n:24, label:"3.4", title:"Repeat Sign, 1st and 2nd Endings", unit:3, book:1, time:15, kw:["repeat","endings"]},
 {n:25, label:"3.5", title:"D.C., D.S., Coda and Fine", unit:3, book:1, time:15, kw:["da capo","dal segno","coda","fine","road map"]},
 {n:26, label:"4.1", title:"Tetrachords and Major Scales", unit:4, book:2, time:15, kw:["tetrachord","major scale"]},
 {n:27, label:"4.2", title:"The Sharp Scales — G and D Major", unit:4, book:2, time:15, kw:["G major","D major","sharp scales"]},
 {n:28, label:"4.3", title:"The Flat Scales — F and B♭ Major", unit:4, book:2, time:15, kw:["F major","Bb major","flat scales"]},
 {n:29, label:"4.4", title:"Key Signatures — The Sharp Keys", unit:4, book:2, time:15, kw:["key signature","sharp keys"]},
 {n:30, label:"4.5", title:"Key Signatures — The Flat Keys", unit:4, book:2, time:15, kw:["key signature","flat keys"]},
 {n:31, label:"4.6", title:"Circle of Fifths and Enharmonic Keys", unit:4, book:2, time:15, kw:["circle of fifths","enharmonic","key signatures","twins"]},
 {n:32, label:"4.7", title:"Solfège and Transposition", unit:4, book:2, time:15, kw:["solfege","do re mi","transposition"]},
 {n:33, label:"5.1", title:"Intervals", unit:5, book:2, time:15, kw:["interval","2nd","3rd","distance"]},
 {n:34, label:"5.2", title:"Perfect and Major Intervals", unit:5, book:2, time:15, kw:["perfect","major","interval quality"]},
 {n:35, label:"5.3", title:"Minor Intervals", unit:5, book:2, time:15, kw:["minor interval"]},
 {n:36, label:"5.4", title:"Augmented and Diminished Intervals", unit:5, book:2, time:15, kw:["augmented","diminished","interval"]},
 {n:37, label:"5.5", title:"Interval Inversions and Compound Intervals", unit:5, book:4, time:15, kw:["inversion","compound interval","rule of 9"]},
 {n:38, label:"6.1", title:"Sixteenth Notes", unit:6, book:2, time:15, kw:["sixteenth","semiquaver"]},
 {n:39, label:"6.2", title:"Sixteenth Rests", unit:6, book:2, time:15, kw:["sixteenth rest"]},
 {n:40, label:"6.3", title:"Dotted Eighth Notes", unit:6, book:2, time:15, kw:["dotted eighth","swing"]},
 {n:41, label:"6.4", title:"Common Time and Cut Time (Alla Breve)", unit:6, book:2, time:15, kw:["common time","cut time","alla breve"]},
 {n:42, label:"6.5", title:"3/8 and 6/8 Time Signatures", unit:6, book:2, time:15, kw:["3/8","6/8","compound meter"]},
 {n:43, label:"6.6", title:"Compound Meter Expanded", unit:6, book:4, time:15, kw:["compound meter","6/8","9/8","12/8","conducting"]},
 {n:44, label:"6.7", title:"Eighth Note Triplets", unit:6, book:2, time:15, kw:["triplet"]},
 {n:45, label:"6.8", title:"Tuplets: Triplets and Duplets", unit:6, book:4, time:15, kw:["tuplet","triplet","duplet","quintuplet","sextuplet"]},
 {n:46, label:"6.9", title:"Incomplete Measures (Pick-up Notes) and Syncopation", unit:6, book:2, time:15, kw:["pickup","anacrusis","syncopation"]},
 {n:47, label:"6.10", title:"Syncopation", unit:6, book:4, time:15, kw:["syncopation","off-beat","tie","anticipation"]},
 {n:48, label:"6.11", title:"Asymmetrical and Changing Meter", unit:6, book:4, time:15, kw:["5/4","7/8","mixed meter","additive"]},
 {n:49, label:"7.1", title:"Triads", unit:7, book:2, time:15, kw:["triad","chord","root third fifth"]},
 {n:50, label:"7.2", title:"Scale Degree Names", unit:7, book:2, time:15, kw:["tonic","dominant","subdominant","scale degrees"]},
 {n:51, label:"7.3", title:"Primary and Major Triads", unit:7, book:2, time:15, kw:["primary triads","I IV V"]},
 {n:52, label:"7.4", title:"Diatonic Triads", unit:7, book:4, time:15, kw:["diatonic triads","chord quality","seven triads"]},
 {n:53, label:"7.5", title:"Minor Triads", unit:7, book:3, time:15, kw:["minor triad"]},
 {n:54, label:"7.6", title:"Augmented and Diminished Triads", unit:7, book:3, time:15, kw:["augmented","diminished","triads"]},
 {n:55, label:"7.7", title:"Triads — 1st Inversion", unit:7, book:3, time:15, kw:["inversion","first inversion"]},
 {n:56, label:"7.8", title:"Triads — 2nd Inversion", unit:7, book:3, time:15, kw:["second inversion"]},
 {n:57, label:"7.9", title:"Figured Bass", unit:7, book:3, time:15, kw:["figured bass","numbers"]},
 {n:58, label:"8.1", title:"Minor Scales", unit:8, book:3, time:15, kw:["minor scale","relative minor"]},
 {n:59, label:"8.2", title:"Natural, Harmonic and Melodic Minor Scales", unit:8, book:3, time:15, kw:["natural minor","harmonic minor","melodic minor"]},
 {n:60, label:"8.3", title:"The Primary Triads in Minor Keys", unit:8, book:3, time:15, kw:["minor primary triads","i iv V"]},
 {n:61, label:"8.4", title:"Modes Related to the Major Scale: Ionian, Mixolydian and Lydian", unit:8, book:3, time:15, kw:["modes","ionian","mixolydian","lydian"]},
 {n:62, label:"8.5", title:"Modes Related to the Minor Scale: Aeolian, Dorian, Phrygian, Locrian", unit:8, book:3, time:15, kw:["aeolian","dorian","phrygian","locrian"]},
 {n:63, label:"8.6", title:"Modes in Practice", unit:8, book:4, time:15, kw:["modes","dorian","mixolydian","lydian","phrygian"]},
 {n:64, label:"8.7", title:"Pentatonic Scales", unit:8, book:4, time:15, kw:["pentatonic","gapped scale"]},
 {n:65, label:"8.8", title:"Chromatic Scale", unit:8, book:2, time:15, kw:["chromatic","half steps"]},
 {n:66, label:"8.9", title:"Whole-Tone and Chromatic Scales", unit:8, book:4, time:15, kw:["whole-tone","whole tone","chromatic","symmetrical"]},
 {n:67, label:"9.1", title:"Roman Numeral Analysis", unit:9, book:4, time:15, kw:["roman numerals","harmonic function","tonic","predominant","dominant"]},
 {n:68, label:"9.2", title:"Cadences", unit:9, book:4, time:15, kw:["cadence","authentic","half","plagal","deceptive","PAC","IAC"]},
 {n:69, label:"9.3", title:"Major Chord Progressions", unit:9, book:3, time:15, kw:["progression","I IV V7"]},
 {n:70, label:"9.4", title:"Minor Chord Progressions", unit:9, book:3, time:15, kw:["minor progression"]},
 {n:71, label:"10.1", title:"The V7 (Dominant 7th) Chord", unit:10, book:2, time:15, kw:["V7","dominant seventh"]},
 {n:72, label:"10.2", title:"V7 Chord — 1st, 2nd and 3rd Inversions", unit:10, book:3, time:15, kw:["V7 inversions"]},
 {n:73, label:"10.3", title:"Five Common Seventh-Chord Types", unit:10, book:4, time:15, kw:["seventh chords","maj7","m7","dominant 7","half-diminished","diminished 7"]},
 {n:74, label:"10.4", title:"Seventh-Chord Inversions", unit:10, book:4, time:15, kw:["inversion","6/5","4/3","4/2","figured bass"]},
 {n:75, label:"10.5", title:"Lead Sheet Reading (Chord Symbols)", unit:10, book:4, time:15, kw:["lead sheet","lead-sheet","chord symbols","sus","add9","slash chord"]},
 {n:76, label:"11.1", title:"Common Chord Progressions", unit:11, book:4, time:15, kw:["ii-V-I","circle progression","pop loop","harmonic rhythm"]},
 {n:77, label:"11.2", title:"Voice-Leading Basics", unit:11, book:4, time:15, kw:["SATB","voice leading","spacing","voice crossing","parallel fifths"]},
 {n:78, label:"11.3", title:"Harmonizing a Melody in a Major Key", unit:11, book:3, time:15, kw:["harmonize","melody","major"]},
 {n:79, label:"11.4", title:"Harmonizing a Melody in a Minor Key", unit:11, book:3, time:15, kw:["harmonize","minor"]},
 {n:80, label:"11.5", title:"Broken Chords and Arpeggiated Accompaniments", unit:11, book:3, time:15, kw:["broken chord","arpeggio","alberti"]},
 {n:81, label:"11.6", title:"Composing a Melody in a Major Key", unit:11, book:3, time:15, kw:["compose","melody","major"]},
 {n:82, label:"11.7", title:"Composing a Melody in a Minor Key", unit:11, book:3, time:15, kw:["compose","minor"]},
 {n:83, label:"11.8", title:"12-Bar Blues Chord Progression", unit:11, book:3, time:15, kw:["blues","12-bar"]},
 {n:84, label:"11.9", title:"The Blues Scale", unit:11, book:3, time:15, kw:["blues scale"]},
 {n:85, label:"12.1", title:"Passing and Neighboring Tones", unit:12, book:3, time:15, kw:["passing tone","neighbor tone","nonharmonic"]},
 {n:86, label:"12.2", title:"Nonchord Tones Expanded", unit:12, book:4, time:15, kw:["nonchord tones","suspension","appoggiatura","escape tone","anticipation","pedal point","retardation"]},
 {n:87, label:"12.3", title:"Ornaments", unit:12, book:4, time:15, kw:["trill","mordent","turn","grace notes"]},
 {n:88, label:"13.1", title:"Secondary Dominants", unit:13, book:4, time:15, kw:["secondary dominant","V/V","tonicization","applied chords"]},
 {n:89, label:"13.2", title:"Modulation", unit:13, book:4, time:15, kw:["modulation","pivot chord","closely related keys","phrase modulation"]},
 {n:90, label:"14.1", title:"Basic Forms of Music — Motive and Phrase", unit:14, book:3, time:15, kw:["motive","phrase","form"]},
 {n:91, label:"14.2", title:"Phrases and Periods", unit:14, book:4, time:15, kw:["period","antecedent","consequent","parallel","contrasting"]},
 {n:92, label:"14.3", title:"Melodic Sequence", unit:14, book:4, time:15, kw:["sequence","tonal","exact","motive development"]},
 {n:93, label:"14.4", title:"Texture", unit:14, book:4, time:15, kw:["texture","monophonic","homophonic","polyphonic","heterophonic"]},
 {n:94, label:"14.5", title:"Binary Form", unit:14, book:3, time:15, kw:["binary","AB form","sectional","continuous","rounded binary"]},
 {n:95, label:"14.6", title:"ABA (Ternary) Form", unit:14, book:3, time:15, kw:["ternary","ABA form"]},
 {n:96, label:"14.7", title:"Rondo Form", unit:14, book:3, time:15, kw:["rondo"]},
 {n:97, label:"14.8", title:"Common Song Forms", unit:14, book:4, time:15, kw:["strophic","through-composed","AABA","verse-chorus","bridge"]},
 {n:98, label:"14.9", title:"Theme and Variations", unit:14, book:4, time:15, kw:["theme","variations","minore","ornamentation"]},
 {n:99, label:"14.10", title:"Sonata Form", unit:14, book:4, time:15, kw:["sonata form","exposition","development","recapitulation","coda"]},
 {n:100, label:"14.11", title:"Instrumental Forms and Multi-Movement Genres", unit:14, book:4, time:15, kw:["minuet","trio","scherzo","march","concerto","cadenza","symphony"]},
 {n:101, label:"15.1", title:"Leading-Tone Chords", unit:15, book:4, time:15, kw:["vii dim","leading-tone seventh","diminished seventh","dominant function"]},
 {n:102, label:"15.2", title:"The Neapolitan Chord", unit:15, book:4, time:15, kw:["neapolitan","flat II","N6","predominant"]},
 {n:103, label:"15.3", title:"Augmented-Sixth Chords", unit:15, book:4, time:15, kw:["augmented sixth","augmented-sixth","italian","french","german"]},
 {n:104, label:"15.4", title:"Borrowed Chords and Modal Mixture", unit:15, book:4, time:15, kw:["modal mixture","borrowed chords","parallel keys","picardy third"]},
 {n:105, label:"15.5", title:"Extended Chords", unit:15, book:4, time:15, kw:["ninth","eleventh","thirteenth","extensions"]},
 {n:106, label:"15.6", title:"Modern Color Chords: Sus, Add, and Sixth Chords", unit:15, book:4, time:15, kw:["sus2","sus4","add9","add2","sixth chord","6/9"]},
 {n:107, label:"15.7", title:"Introduction to Reharmonization: Substitution and Chromatic Color", unit:15, book:4, time:16, kw:["reharmonization","functional families","diatonic substitution","tritone substitution","chromatic mediant","altered dominant"]}
];
const UNITS=[
 {unit:1, name:"Basic Concepts", lessons:[1,9]},
 {unit:2, name:"Rhythm I", lessons:[10,20]},
 {unit:3, name:"Expression Marks", lessons:[21,25]},
 {unit:4, name:"Major Scales and Key Signatures", lessons:[26,32]},
 {unit:5, name:"Intervals", lessons:[33,37]},
 {unit:6, name:"Rhythm II", lessons:[38,48]},
 {unit:7, name:"Triads", lessons:[49,57]},
 {unit:8, name:"Minor Scales and Modes", lessons:[58,66]},
 {unit:9, name:"Roman Numerals and Cadences", lessons:[67,70]},
 {unit:10, name:"Seventh Chords", lessons:[71,75]},
 {unit:11, name:"Harmony Foundations", lessons:[76,84]},
 {unit:12, name:"Nonchord Tones and Ornaments", lessons:[85,87]},
 {unit:13, name:"Tonicization and Modulation", lessons:[88,89]},
 {unit:14, name:"Form and Texture", lessons:[90,100]},
 {unit:15, name:"Chromatic and Contemporary Harmony", lessons:[101,107]}
];
/* built lessons so far (index pages link only these) */
const BUILT_THROUGH=107;
const LESSON_CONTENT={}; /* filled by content/lesson-NN.js */
