/* Music Fundamentals — master lesson list (source: AEMT Books 1-3 TOC, verified 2026-07-03)
   Drives ALL navigation. Titles/order locked to the textbook (DD-12). */
const LESSONS=[
 {n:1, title:"The Staff, Notes and Pitches", unit:1, book:1, time:15, kw:["staff","note","pitch","lines","spaces"]},
 {n:2, title:"Treble Clef and Staff", unit:1, book:1, time:15, kw:["treble","clef","G clef","EGBDF","FACE"]},
 {n:3, title:"Bass Clef and Staff", unit:1, book:1, time:15, kw:["bass","clef","F clef","GBDFA","ACEG"]},
 {n:4, title:"The Grand Staff and Ledger Lines (the middle notes)", unit:1, book:1, time:15, kw:["grand staff","ledger","middle C","brace"]},
 {n:5, title:"Ledger Lines (low and high notes)", unit:1, book:1, time:15, kw:["ledger","lines","high","low"]},
 {n:6, title:"Note Values", unit:2, book:1, time:15, kw:["whole","half","quarter","note values","rhythm"]},
 {n:7, title:"Measure, Bar Line and Double Bar", unit:2, book:1, time:15, kw:["measure","bar line","double bar"]},
 {n:8, title:"4/4 Time Signature and Note Values", unit:2, book:1, time:15, kw:["time signature","4/4","meter"]},
 {n:9, title:"Whole, Half and Quarter Rests", unit:2, book:1, time:15, kw:["rest","silence"]},
 {n:10, title:"2/4 Time Signature", unit:3, book:1, time:15, kw:["2/4","time signature"]},
 {n:11, title:"3/4 Time Signature", unit:3, book:1, time:15, kw:["3/4","waltz","time signature"]},
 {n:12, title:"Dotted Half Note", unit:3, book:1, time:15, kw:["dotted","half note","dot"]},
 {n:13, title:"Ties and Slurs", unit:3, book:1, time:15, kw:["tie","slur","legato"]},
 {n:14, title:"Repeat Sign, 1st and 2nd Endings", unit:4, book:1, time:15, kw:["repeat","endings"]},
 {n:15, title:"Eighth Notes", unit:4, book:1, time:15, kw:["eighth","beam","flag"]},
 {n:16, title:"Eighth Rests", unit:4, book:1, time:15, kw:["eighth rest"]},
 {n:17, title:"Dotted Quarter Note", unit:4, book:1, time:15, kw:["dotted quarter"]},
 {n:18, title:"Dynamic Signs", unit:5, book:1, time:15, kw:["dynamics","forte","piano","crescendo"]},
 {n:19, title:"Tempo Marks", unit:5, book:1, time:15, kw:["tempo","allegro","andante","adagio"]},
 {n:20, title:"Articulation", unit:5, book:1, time:15, kw:["staccato","accent","legato","fermata"]},
 {n:21, title:"D.C., D.S., Coda and Fine", unit:5, book:1, time:15, kw:["da capo","dal segno","coda","fine","road map"]},
 {n:22, title:"Flats", unit:6, book:1, time:15, kw:["flat","accidental"]},
 {n:23, title:"Sharps", unit:6, book:1, time:15, kw:["sharp","accidental"]},
 {n:24, title:"Naturals", unit:6, book:1, time:15, kw:["natural","accidental"]},
 {n:25, title:"Whole Steps, Half Steps and Enharmonic Notes", unit:6, book:1, time:15, kw:["whole step","half step","enharmonic"]},
 {n:26, title:"Tetrachords and Major Scales", unit:7, book:2, time:15, kw:["tetrachord","major scale"]},
 {n:27, title:"The Sharp Scales — G and D Major", unit:7, book:2, time:15, kw:["G major","D major","sharp scales"]},
 {n:28, title:"The Flat Scales — F and B♭ Major", unit:7, book:2, time:15, kw:["F major","Bb major","flat scales"]},
 {n:29, title:"Key Signatures — The Sharp Keys", unit:7, book:2, time:15, kw:["key signature","sharp keys"]},
 {n:30, title:"Key Signatures — The Flat Keys", unit:7, book:2, time:15, kw:["key signature","flat keys"]},
 {n:31, title:"The Remaining Major Scales with Key Signatures", unit:8, book:2, time:15, kw:["major scales","key signatures"]},
 {n:32, title:"Chromatic Scale", unit:8, book:2, time:15, kw:["chromatic","half steps"]},
 {n:33, title:"Intervals", unit:8, book:2, time:15, kw:["interval","2nd","3rd","distance"]},
 {n:34, title:"Circle of Fifths", unit:8, book:2, time:15, kw:["circle of fifths"]},
 {n:35, title:"Perfect and Major Intervals", unit:9, book:2, time:15, kw:["perfect","major","interval quality"]},
 {n:36, title:"Minor Intervals", unit:9, book:2, time:15, kw:["minor interval"]},
 {n:37, title:"Augmented and Diminished Intervals", unit:9, book:2, time:15, kw:["augmented","diminished","interval"]},
 {n:38, title:"Solfège and Transposition", unit:9, book:2, time:15, kw:["solfege","do re mi","transposition"]},
 {n:39, title:"Sixteenth Notes", unit:10, book:2, time:15, kw:["sixteenth","semiquaver"]},
 {n:40, title:"Sixteenth Rests", unit:10, book:2, time:15, kw:["sixteenth rest"]},
 {n:41, title:"Dotted Eighth Notes", unit:10, book:2, time:15, kw:["dotted eighth","swing"]},
 {n:42, title:"Common Time and Cut Time (Alla Breve)", unit:10, book:2, time:15, kw:["common time","cut time","alla breve"]},
 {n:43, title:"3/8 and 6/8 Time Signatures", unit:11, book:2, time:15, kw:["3/8","6/8","compound meter"]},
 {n:44, title:"3/8 and 6/8 Time Signatures at Fast Tempos", unit:11, book:2, time:15, kw:["6/8 fast","compound"]},
 {n:45, title:"Eighth Note Triplets", unit:11, book:2, time:15, kw:["triplet"]},
 {n:46, title:"Incomplete Measures (Pick-up Notes) and Syncopation", unit:11, book:2, time:15, kw:["pickup","anacrusis","syncopation"]},
 {n:47, title:"Triads", unit:12, book:2, time:15, kw:["triad","chord","root third fifth"]},
 {n:48, title:"Primary and Major Triads", unit:12, book:2, time:15, kw:["primary triads","I IV V"]},
 {n:49, title:"Scale Degree Names", unit:12, book:2, time:15, kw:["tonic","dominant","subdominant","scale degrees"]},
 {n:50, title:"The V7 (Dominant 7th) Chord", unit:12, book:2, time:15, kw:["V7","dominant seventh"]},
 {n:51, title:"Triads — 1st Inversion", unit:13, book:3, time:15, kw:["inversion","first inversion"]},
 {n:52, title:"Triads — 2nd Inversion", unit:13, book:3, time:15, kw:["second inversion"]},
 {n:53, title:"V7 Chord — 1st, 2nd and 3rd Inversions", unit:13, book:3, time:15, kw:["V7 inversions"]},
 {n:54, title:"Figured Bass", unit:13, book:3, time:15, kw:["figured bass","numbers"]},
 {n:55, title:"Major Chord Progressions", unit:13, book:3, time:15, kw:["progression","I IV V7"]},
 {n:56, title:"Minor Scales", unit:14, book:3, time:15, kw:["minor scale","relative minor"]},
 {n:57, title:"Natural, Harmonic and Melodic Minor Scales", unit:14, book:3, time:15, kw:["natural minor","harmonic minor","melodic minor"]},
 {n:58, title:"Minor Triads", unit:14, book:3, time:15, kw:["minor triad"]},
 {n:59, title:"Augmented and Diminished Triads", unit:14, book:3, time:15, kw:["augmented","diminished","triads"]},
 {n:60, title:"The Primary Triads in Minor Keys", unit:15, book:3, time:15, kw:["minor primary triads","i iv V"]},
 {n:61, title:"Minor Chord Progressions", unit:15, book:3, time:15, kw:["minor progression"]},
 {n:62, title:"Modes Related to the Major Scale: Ionian, Mixolydian and Lydian", unit:15, book:3, time:15, kw:["modes","ionian","mixolydian","lydian"]},
 {n:63, title:"Modes Related to the Minor Scale: Aeolian, Dorian, Phrygian, Locrian", unit:15, book:3, time:15, kw:["aeolian","dorian","phrygian","locrian"]},
 {n:64, title:"Harmonizing a Melody in a Major Key", unit:16, book:3, time:15, kw:["harmonize","melody","major"]},
 {n:65, title:"Broken Chords and Arpeggiated Accompaniments", unit:16, book:3, time:15, kw:["broken chord","arpeggio","alberti"]},
 {n:66, title:"Passing and Neighboring Tones", unit:16, book:3, time:15, kw:["passing tone","neighbor tone","nonharmonic"]},
 {n:67, title:"Composing a Melody in a Major Key", unit:16, book:3, time:15, kw:["compose","melody","major"]},
 {n:68, title:"Harmonizing a Melody in a Minor Key", unit:17, book:3, time:15, kw:["harmonize","minor"]},
 {n:69, title:"Composing a Melody in a Minor Key", unit:17, book:3, time:15, kw:["compose","minor"]},
 {n:70, title:"12-Bar Blues Chord Progression", unit:17, book:3, time:15, kw:["blues","12-bar"]},
 {n:71, title:"The Blues Scale", unit:17, book:3, time:15, kw:["blues scale"]},
 {n:72, title:"Basic Forms of Music — Motive and Phrase", unit:18, book:3, time:15, kw:["motive","phrase","form"]},
 {n:73, title:"Binary Form", unit:18, book:3, time:15, kw:["binary","AB form","sectional","continuous","rounded binary"]},
 {n:74, title:"ABA (Ternary) Form", unit:18, book:3, time:15, kw:["ternary","ABA form"]},
 {n:75, title:"Rondo Form", unit:18, book:3, time:15, kw:["rondo"]},
 {n:76, title:"Compound Meter Expanded", unit:19, book:4, time:15, kw:["compound meter","6/8","9/8","12/8","conducting"]},
 {n:77, title:"Tuplets: Triplets and Duplets", unit:19, book:4, time:15, kw:["tuplet","triplet","duplet","quintuplet","sextuplet"]},
 {n:78, title:"Syncopation", unit:19, book:4, time:15, kw:["syncopation","off-beat","tie","anticipation"]},
 {n:79, title:"Asymmetrical and Changing Meter", unit:19, book:4, time:15, kw:["5/4","7/8","mixed meter","additive"]},
 {n:80, title:"Modes in Practice", unit:20, book:4, time:15, kw:["modes","dorian","mixolydian","lydian","phrygian"]},
 {n:81, title:"Pentatonic Scales", unit:20, book:4, time:15, kw:["pentatonic","gapped scale"]},
 {n:82, title:"Whole-Tone and Chromatic Scales", unit:20, book:4, time:15, kw:["whole-tone","whole tone","chromatic","symmetrical"]},
 {n:83, title:"Interval Inversions and Compound Intervals", unit:20, book:4, time:15, kw:["inversion","compound interval","rule of 9"]},
 {n:84, title:"Transposition", unit:21, book:4, time:15, kw:["transposition","transposing instruments","key change"]},
 {n:85, title:"Diatonic Triads", unit:21, book:4, time:15, kw:["diatonic triads","chord quality","seven triads"]},
 {n:86, title:"Roman Numeral Analysis", unit:21, book:4, time:15, kw:["roman numerals","harmonic function","tonic","predominant","dominant"]},
 {n:87, title:"Cadences", unit:21, book:4, time:15, kw:["cadence","authentic","half","plagal","deceptive","PAC","IAC"]},
 {n:88, title:"Phrases and Periods", unit:22, book:4, time:15, kw:["period","antecedent","consequent","parallel","contrasting"]},
 {n:89, title:"Melodic Sequence", unit:22, book:4, time:15, kw:["sequence","tonal","exact","motive development"]},
 {n:90, title:"Texture", unit:22, book:4, time:15, kw:["texture","monophonic","homophonic","polyphonic","heterophonic"]},
 {n:91, title:"Common Song Forms", unit:22, book:4, time:15, kw:["strophic","through-composed","AABA","verse-chorus","bridge"]},
 {n:92, title:"Five Common Seventh-Chord Types", unit:23, book:4, time:15, kw:["seventh chords","maj7","m7","dominant 7","half-diminished","diminished 7"]},
 {n:93, title:"Lead Sheet Reading (Chord Symbols)", unit:23, book:4, time:15, kw:["lead sheet","lead-sheet","chord symbols","sus","add9","slash chord"]},
 {n:94, title:"Seventh-Chord Inversions", unit:23, book:4, time:15, kw:["inversion","6/5","4/3","4/2","figured bass"]},
 {n:95, title:"Common Chord Progressions", unit:23, book:4, time:15, kw:["ii-V-I","circle progression","pop loop","harmonic rhythm"]},
 {n:96, title:"Nonchord Tones Expanded", unit:24, book:4, time:15, kw:["nonchord tones","suspension","appoggiatura","escape tone","anticipation","pedal point","retardation"]},
 {n:97, title:"Voice-Leading Basics", unit:24, book:4, time:15, kw:["SATB","voice leading","spacing","voice crossing","parallel fifths"]},
 {n:98, title:"Secondary Dominants", unit:24, book:4, time:15, kw:["secondary dominant","V/V","tonicization","applied chords"]},
 {n:99, title:"Modulation", unit:24, book:4, time:15, kw:["modulation","pivot chord","closely related keys","phrase modulation"]},
 {n:100, title:"Ornaments", unit:25, book:4, time:15, kw:["trill","mordent","turn","grace notes"]},
 {n:101, title:"Theme and Variations", unit:25, book:4, time:15, kw:["theme","variations","minore","ornamentation"]},
 {n:102, title:"Sonata Form", unit:25, book:4, time:15, kw:["sonata form","exposition","development","recapitulation","coda"]},
 {n:103, title:"Instrumental Forms and Multi-Movement Genres", unit:25, book:4, time:15, kw:["minuet","trio","scherzo","march","concerto","cadenza","symphony"]},
 {n:104, title:"Leading-Tone Chords", unit:26, book:4, time:15, kw:["vii dim","leading-tone seventh","diminished seventh","dominant function"]},
 {n:105, title:"The Neapolitan Chord", unit:26, book:4, time:15, kw:["neapolitan","flat II","N6","predominant"]},
 {n:106, title:"Augmented-Sixth Chords", unit:26, book:4, time:15, kw:["augmented sixth","augmented-sixth","italian","french","german"]},
 {n:107, title:"Borrowed Chords and Modal Mixture", unit:26, book:4, time:15, kw:["modal mixture","borrowed chords","parallel keys","picardy third"]},
 {n:108, title:"Extended Chords", unit:27, book:4, time:15, kw:["ninth","eleventh","thirteenth","extensions"]},
 {n:109, title:"Modern Color Chords: Sus, Add, and Sixth Chords", unit:27, book:4, time:15, kw:["sus2","sus4","add9","add2","sixth chord","6/9"]},
 {n:110, title:"Introduction to Reharmonization: Substitution and Chromatic Color", unit:27, book:4, time:16, kw:["reharmonization","functional families","diatonic substitution","tritone substitution","chromatic mediant","altered dominant"]}
];
const UNITS=[
 {unit:1, book:1, name:"The Staff and Clefs", lessons:[1,5]},
 {unit:2, book:1, name:"Note Values and 4/4 Time", lessons:[6,9]},
 {unit:3, book:1, name:"More Time Signatures, Dots, Ties and Slurs", lessons:[10,13]},
 {unit:4, book:1, name:"Repeats, Eighth Notes and Dotted Quarters", lessons:[14,17]},
 {unit:5, book:1, name:"Expression Marks", lessons:[18,21]},
 {unit:6, book:1, name:"Accidentals and Steps", lessons:[22,25]},
 {unit:7, book:2, name:"Major Scales and Key Signatures", lessons:[26,30]},
 {unit:8, book:2, name:"Remaining Scales, Chromatic, Intervals, Circle of Fifths", lessons:[31,34]},
 {unit:9, book:2, name:"Interval Qualities, Solfège and Transposition", lessons:[35,38]},
 {unit:10, book:2, name:"Sixteenth Notes and Cut Time", lessons:[39,42]},
 {unit:11, book:2, name:"Compound Meter, Triplets and Syncopation", lessons:[43,46]},
 {unit:12, book:2, name:"Triads and the V7 Chord", lessons:[47,50]},
 {unit:13, book:3, name:"Inversions, Figured Bass and Progressions", lessons:[51,55]},
 {unit:14, book:3, name:"Minor Scales and Triad Qualities", lessons:[56,59]},
 {unit:15, book:3, name:"Minor Keys and Modes", lessons:[60,63]},
 {unit:16, book:3, name:"Harmonizing and Composing in Major", lessons:[64,67]},
 {unit:17, book:3, name:"Minor Harmonization and the Blues", lessons:[68,71]},
 {unit:18, book:3, name:"Form", lessons:[72,75]},
 {unit:19, book:4, name:"Rhythm & Meter Expanded", lessons:[76,79]},
 {unit:20, book:4, name:"Scales & Modes", lessons:[80,83]},
 {unit:21, book:4, name:"Keys & Harmony Foundations", lessons:[84,87]},
 {unit:22, book:4, name:"Musical Structure", lessons:[88,91]},
 {unit:23, book:4, name:"Seventh Chords", lessons:[92,95]},
 {unit:24, book:4, name:"Harmony in Practice", lessons:[96,99]},
 {unit:25, book:4, name:"Musical Expression & Forms", lessons:[100,103]},
 {unit:26, book:4, name:"Chromatic Harmony", lessons:[104,107]},
 {unit:27, book:4, name:"Expanded Tonality", lessons:[108,111]}
];
/* built lessons so far (index pages link only these) */
const BUILT_THROUGH=110;
const LESSON_CONTENT={}; /* filled by content/lesson-NN.js */
